SELECT 

distinct PLAN_ID AS Risk_Ass_Plan_Id,
OBJECT_ID as Risk_Ass_Id,
SCN_NAME as Perspective,
PROGRESS_STATUS as Ass_Status,
RISK_NAME as OR_Tax,
RISK_CATEGORIES as RISK_CATEGORIES,
RISK_OWNERS as RISK_OWNERS,
DUMMY10 AS Own_Org,
DUMMY9 AS Ass_Bus_Owner,
DUMMY8 AS Bus_Org,
RISK_LEVEL as RISK_LEVEL,
CAL_INH_RISK_RATING as CAL_INH_RISK_RATING,
IS_INH_OVERRIDEN as IS_INH_OVERRIDEN,
FINAL_INHERENT_RATING as FINAL_INHERENT_RATING,
CAL_CONTROL_RATING as CAL_CONTROL_RATING,
IS_CONTROL_OVERRIDEN as IS_CONTROL_OVERRIDEN,
FINAL_OVERALL_CONTROL_RATING as FINAL_OVERALL_CONTROL_RATING,
FINAL_RESIDUAL_RATING as FINAL_RESIDUAL_RATING,
RESIDUAL_TREND as RESIDUAL_TREND,
DUMMY15 as is_residual_risk_within
,ASSMNT_DUE_DATE
,ASSESSED_ON
,ASSESSED_BY
,ASSMNT_APPROVER as Level_1_Appr
,level2_approver as level_2_Appr,
DUMMY11 AS remediation_actions,
DUMMY11 as definition_remediation_act,
---columns to add

                     --as RISK_ASSESSMENT_TYPE(10)(Need to be added in package also)
					 --Related risks(11)(---//----)
CAL_RES_RISK_RATING,    --as rsk_override_score_res(19)
IS_RES_OVERRIDEN  ,     --as rsk_override_score_res(20)
12 months            ---a_taxonomy_assessment_has_ther(24)




--Additional Columns


PLAN_NAME as Risk_Ass_Plan_Name,


PUR_SCOPE as purpose_scope,
A_EXECUTIVE_SUMMARY as EXECUTIVE_SUMMARY,
IMMATERIAL_RISK as IMMATERIAL_RISK,



FACTOR_REP_RATING as FACTOR_REP_RATING,
FACTOR_REG_RATING as FACTOR_REG_RATING,
FACTOR_FIN_RATING as FACTOR_FIN_RATING,
FACTOR_MAR_RATING as FACTOR_MAR_RATING,
FACTOR_CLI_RATING as FACTOR_CLI_RATING,


CONTRL_DES_RATING as CONTRL_DES_RATING,
CONTRL_OPR_RATING as CONTRL_OPR_RATING,
CONTRL_ISS_RATING as CONTRL_ISS_RATING,
CONTRL_POL_RATING as CONTRL_POL_RATING,
CONTRL_COL_RATING as CONTRL_COL_RATING,


DUMMY11 AS risk_driver,
DUMMY12 as or_level_3_taxonomy,



,null as COMPLETED_ON

,null as APPROVED_ON

,'View Risk Assessment Comments History Report' as ass_comment_hist
,'View Risk Assessment Plan Comments History Report' AS plan_comment_hist,'<a href=''#''>One Page Report </a>' as JASPER
,DUMMY7



  FROM TABLE(MS_RSX_REPORT_UTILS_PKG.get_assmnt_rep(:PERSPECTIVE))
WHERE NVL(PLAN_NAME,'2222') IN (SELECT COLUMN_VALUE FROM  TABLE (ms_apps_utilities.SPLIT_STRING(NVL(NVL(:pv_plan_name,PLAN_NAME),'2222'),',')))
AND NVL(OBJECT_ID,'2222') IN (SELECT COLUMN_VALUE FROM  TABLE (ms_apps_utilities.SPLIT_STRING(NVL(NVL(:pv_assmnt_id,OBJECT_ID),'2222'),',')))
AND NVL(PROGRESS_STATUS,'2222') IN (SELECT COLUMN_VALUE FROM  TABLE (ms_apps_utilities.SPLIT_STRING(NVL(NVL(:pv_ass_status,PROGRESS_STATUS),'2222'),',')))
AND NVL(DUMMY1,'2222') IN (SELECT COLUMN_VALUE FROM  TABLE (ms_apps_utilities.SPLIT_STRING(NVL(NVL(:pv_owner_org,DUMMY1),'2222'),',')))
AND NVL(DUMMY2,'2222') IN (SELECT COLUMN_VALUE FROM  TABLE (ms_apps_utilities.SPLIT_STRING(NVL(NVL(:pv_ass_business_owner,DUMMY2),'2222'),',')))
AND NVL(DUMMY3,'2222') IN (SELECT COLUMN_VALUE FROM  TABLE (ms_apps_utilities.SPLIT_STRING(NVL(NVL(:pv_assessed_org,DUMMY3),'2222'),',')))
AND (:IP_INHERENT_RATING IS NULL OR ','||:IP_INHERENT_RATING||',' LIKE '%,'||CAL_INH_RISK_RATING||',%')
AND (:IP_CONTROL_ENVI_RATING IS NULL OR ','||:IP_CONTROL_ENVI_RATING||',' LIKE '%,'||CAL_CONTROL_RATING||',%')
AND (:IP_RESIDUAL_RATING IS NULL OR ','||:IP_RESIDUAL_RATING||',' LIKE '%,'||FINAL_RESIDUAL_RATING||',%')
AND NVL(DUMMY15,'is_RESIDUAL_RAT_within')=NVL(NVL(:is_RESIDUAL_RAT_within,DUMMY15),'is_RESIDUAL_RAT_within')
AND NVL(DUMMY7,'2222') IN (SELECT COLUMN_VALUE FROM  TABLE (ms_apps_utilities.SPLIT_STRING(NVL(NVL(:pv_RESIDUAL_TREND,DUMMY7),'2222'),',')))
AND  TRUNC(NVL(TO_DATE(ASSESSED_ON,'DD-MM-YY'),SYSDATE)) >= NVL(NVL(:pv_assessed_after,(TO_DATE(ASSESSED_ON,'DD-MM-YY'))),SYSDATE)
AND TRUNC(NVL(TO_DATE(ASSESSED_ON,'DD-MM-YY'),SYSDATE)) <= NVL(NVL(:pv_assessed_before,(TO_DATE(ASSESSED_ON,'DD-MM-YY'))),SYSDATE)
AND NVL(ASSESSED_BY,'2222') IN (SELECT COLUMN_VALUE FROM  TABLE (ms_apps_utilities.SPLIT_STRING(NVL(NVL(:pv_ASSESSED_BY,ASSESSED_BY),'2222'),',')))
AND NVL(REVIEWER,'2222') IN (SELECT COLUMN_VALUE FROM  TABLE (ms_apps_utilities.SPLIT_STRING(NVL(NVL(:pv_l1_app,REVIEWER),'2222'),',')))
AND NVL('l2_app','2222') IN (SELECT COLUMN_VALUE FROM  TABLE (ms_apps_utilities.SPLIT_STRING(NVL(NVL(:pv_l2_app,'l2_app'),'2222'),',')))