SELECT distinct PLAN_ID AS Risk_Ass_Plan_Id,
PLAN_NAME as Risk_Ass_Plan_Name,
OBJECT_ID as Risk_Ass_Id,
SCN_NAME as Perspective,
PROGRESS_STATUS as Ass_Status,
DUMMY10 AS Own_Org,
DUMMY9 AS Ass_Bus_Owner,
DUMMY8 AS Bus_Org,
PUR_SCOPE as purpose_scope,
RISK_NAME as OR_Tax,
RISK_CATEGORIES as RISK_CATEGORIES,
RISK_OWNERS as RISK_OWNERS,
RISK_LEVEL as RISK_LEVEL,
A_EXECUTIVE_SUMMARY as EXECUTIVE_SUMMARY,
IMMATERIAL_RISK as IMMATERIAL_RISK,
CAL_INH_RISK_RATING as CAL_INH_RISK_RATING,
IS_INH_OVERRIDEN as IS_INH_OVERRIDEN,
FINAL_INHERENT_RATING as FINAL_INHERENT_RATING,
CAL_CONTROL_RATING as CAL_CONTROL_RATING,
IS_CONTROL_OVERRIDEN as IS_CONTROL_OVERRIDEN,
FINAL_OVERALL_CONTROL_RATING as FINAL_OVERALL_CONTROL_RATING,
CONTRL_DES_RATING as CONTRL_DES_RATING,
CONTRL_OPR_RATING as CONTRL_OPR_RATING,
CONTRL_ISS_RATING as CONTRL_ISS_RATING,
CONTRL_POL_RATING as CONTRL_POL_RATING,
CONTRL_COL_RATING as CONTRL_COL_RATING,
FINAL_RESIDUAL_RATING as FINAL_RESIDUAL_RATING,
RESIDUAL_TREND as RESIDUAL_TREND,
DUMMY11 AS risk_driver,
DUMMY12 as or_level_3_taxonomy,
DUMMY13 AS remediation_actions,
DUMMY14 as definition_remediation_act,
DUMMY15 as is_residual_risk_within
,ASSMNT_DUE_DATE
,ASSESSED_ON
, ASSESSED_ON as COMPLETED_ON
,ASSESSED_BY
,ASSESSED_ON as APPROVED_ON
,ASSMNT_APPROVER as Level_1_Appr
, level2_approver as level_2_Appr
,DUMMY7
,RISK_ASSESSMENT_TYPE
,RELATED_RISKS
,A_TAXONOMY_ASSESSMENT_HAS_THER
,CAL_RES_RISK_RATING
,IS_RES_OVERRIDEN
  FROM TABLE(MS_RSX_REGISTER_REPORT_PKG.get_assmnt_rep(:PERSPECTIVE))
where NVL(DUMMY10,'2222') IN (SELECT COLUMN_VALUE FROM  TABLE (ms_apps_utilities.SPLIT_STRING(NVL(NVL(:pv_owner_org,DUMMY10),'2222'),',')))
AND NVL(DUMMY9,'2222') IN (SELECT COLUMN_VALUE FROM  TABLE (ms_apps_utilities.SPLIT_STRING(NVL(NVL(:pv_ass_business_owner,DUMMY9),'2222'),',')))
AND NVL(DUMMY8,'2222') IN (SELECT COLUMN_VALUE FROM  TABLE (ms_apps_utilities.SPLIT_STRING(NVL(NVL(:pv_assessed_org,DUMMY8),'2222'),',')))

AND NVL(FINAL_INHERENT_RATING,'2222') IN (SELECT COLUMN_VALUE FROM  TABLE (ms_apps_utilities.SPLIT_STRING(NVL(NVL(:IP_INHERENT_RATING,FINAL_INHERENT_RATING),'2222'),',')))
AND NVL(FINAL_OVERALL_CONTROL_RATING,'2222') IN (SELECT COLUMN_VALUE FROM  TABLE (ms_apps_utilities.SPLIT_STRING(NVL(NVL(:IP_CONTROL_ENVI_RATING,FINAL_OVERALL_CONTROL_RATING),'2222'),',')))
AND NVL(FINAL_RESIDUAL_RATING,'2222') IN (SELECT COLUMN_VALUE FROM  TABLE (ms_apps_utilities.SPLIT_STRING(NVL(NVL(:IP_RESIDUAL_RATING,FINAL_RESIDUAL_RATING),'2222'),',')))
AND NVL(DUMMY15,'is_RESIDUAL_RAT_within')=NVL(NVL(:is_RESIDUAL_RAT_within,DUMMY15),'is_RESIDUAL_RAT_within')
AND NVL(A_TAXONOMY_ASSESSMENT_HAS_THER,'pv_breach')=NVL(NVL(:pv_breach,A_TAXONOMY_ASSESSMENT_HAS_THER),'pv_breach')
AND NVL(RESIDUAL_TREND,'2222') IN (SELECT COLUMN_VALUE FROM  TABLE (ms_apps_utilities.SPLIT_STRING(NVL(NVL(:pv_RESIDUAL_TREND,RESIDUAL_TREND),'2222'),',')))
AND  TRUNC(NVL(TO_DATE(ASSESSED_ON,'DD-MM-YY'),SYSDATE)) >= NVL(NVL(:pv_assessed_after,(TO_DATE(ASSESSED_ON,'DD-MM-YY'))),SYSDATE)
AND TRUNC(NVL(TO_DATE(ASSESSED_ON,'DD-MM-YY'),SYSDATE)) <= NVL(NVL(:pv_assessed_before,(TO_DATE(ASSESSED_ON,'DD-MM-YY'))),SYSDATE)
AND (:pv_assessable_item_type IS NULL OR ','||:pv_assessable_item_type||',' LIKE '%,'||RISK_ASSESSMENT_TYPE||',%')
AND NVL(RISK_LEVEL,'2222') IN (SELECT COLUMN_VALUE FROM  TABLE (ms_apps_utilities.SPLIT_STRING(NVL(NVL(:p_risk_level,RISK_LEVEL),'2222'),',')))
AND NVL(RISK_CATEGORIES,'2222') IN (SELECT COLUMN_VALUE FROM  TABLE (ms_apps_utilities.SPLIT_STRING(NVL(NVL(:pv_risk_category,RISK_CATEGORIES),'2222'),',')))
AND NVL(RELATED_RISKS,'2222') IN (SELECT COLUMN_VALUE FROM  TABLE (ms_apps_utilities.SPLIT_STRING(NVL(NVL(:pv_assessable_item,RELATED_RISKS),'2222'),',')))
AND (:p_status IS NULL OR ''''||:p_status||'''' LIKE '%'''||PROGRESS_STATUS||'''%')
AND NVL(RISK_NAME,'2222') IN (SELECT COLUMN_VALUE FROM  TABLE (ms_apps_utilities.SPLIT_STRING(NVL(NVL(:p_or_taxonomy,RISK_NAME),'2222'),',')))